# name: E2E Cypress Tests

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           build: npm run build
#           start: npm run start-after-120-seconds
#           wait-on: "http://localhost:3000"
#           wait-on-timeout: 130
# name: E2E Cypress Tests

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           build: npm run build
#           start: npm start



name: Cypress Tests

on:
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delay execution
        run: sleep 120

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: sleep 120 && npm run
          wait-on: "http://localhost:3000"
          wait-on-timeout: 130

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
